/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

repositories {
    // Use Maven central for resolving dependencies
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    testImplementation("org.testng:testng:7.10.1")
    testImplementation("org.mockito:mockito-testng:0.5.2")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
