# This is a basic workflow to help you get started with Actions

name: Build and release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup java
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Checkout our code
        uses: actions/checkout@v4
      
      # Setup Gradle - We don't have to do this but it offers advantages
      # See: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      #Run our build using Gradle
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Upload jar / package
          path: app/build/libs
